#### 61. Find the nearest value from a given value in an array 

In [1]:
import numpy as np

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]
arr = np.array([3,6,2,8,4])
value = 5
closest = find_nearest(arr,value)
print(closest)

6


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [2]:
# Define arrays
a = np.array([[1, 2, 3]])  # Shape (1,3)
b = np.array([[4], [5], [6]])  # Shape (3,1)

# Use iterator to compute sum
result = np.zeros((3, 3))  # Result will be (3,3) due to broadcasting
it = np.nditer([a, b, None], op_axes=[[0, -1], [-1, 0], [0, 1]])
for x, y, z in it:
    z[...] = x + y

print(result)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


63. Create an array class that has a name attribute

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', "")

# Example
arr = NamedArray([1, 2, 3], name="my_array")
print(arr)  
print(arr.name)


[1 2 3]
my_array


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [4]:
# Define vector and indices
vector = np.array([0, 1, 2, 3, 4])
indices = np.array([1, 1, 3, 4])

# Add 1 to elements at specified indices
np.add.at(vector, indices, 1)

print(vector)


[0 3 2 4 5]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [5]:
# Define vectors
X = np.array([1, 2, 3, 4])  # Values to accumulate
I = np.array([1, 1, 3, 2])   # Index list
F = np.zeros(4)              # Output array (size should match max index + 1)

# Accumulate elements
np.add.at(F, I, X)

print(F)

[0. 3. 4. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [6]:
# Example image (2x2x3, uint8)
image = np.array([[[255, 0, 0], [0, 255, 0]],
                  [[0, 0, 255], [255, 0, 0]]], dtype=np.uint8)

# Compute unique colors
unique_colors = np.unique(image.reshape(-1, 3), axis=0)
num_unique = len(unique_colors)

print(num_unique)

3


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [7]:
# Example 4D array (shape: 2x3x4x5)
array = np.ones((2, 3, 4, 5))

# Sum over the last two axes
result = np.sum(array, axis=(-2, -1))

print(result.shape)  # Output: (2, 3)
print(result)

(2, 3)
[[20. 20. 20.]
 [20. 20. 20.]]



68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [8]:
# Define vectors
D = np.array([1, 2, 3, 4, 5, 6])  # Data
S = np.array([0, 0, 1, 1, 2, 2])   # Subset indices

# Compute means of subsets
unique_indices = np.unique(S)
means = [np.mean(D[S == i]) for i in unique_indices]

print(means)

[np.float64(1.5), np.float64(3.5), np.float64(5.5)]


69. How to get the diagonal of a dot product? 

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute diagonal of dot product
dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)

print(diagonal)


[19 50]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [10]:
# Input vector
vector = np.array([1, 2, 3, 4, 5])

# Create new vector with 3 zeros between each element
n = len(vector)
result = np.zeros(n + (n - 1) * 3, dtype=vector.dtype)
result[::4] = vector

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [11]:
A = np.ones((5, 5, 3))  # Shape (5,5,3)
B = np.arange(25).reshape(5, 5)  # Shape (5,5)

# Multiply using broadcasting
result = A * B[:, :, np.newaxis]

print(result.shape)


(5, 5, 3)


72. How to swap two rows of an array?

In [12]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 0 and 1
array[[0, 1]] = array[[1, 0]]

print(array)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [13]:
triangles = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5],
                      [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9],
                      [8, 9, 0], [9, 0, 1]])

# Get edges for each triangle
edges = np.concatenate([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [2, 0]]])

# Sort each edge to ensure (a, b) and (b, a) are treated as the same
edges = np.sort(edges, axis=1)

# Find unique edges
unique_edges = np.unique(edges, axis=0)

print(unique_edges)

[[0 1]
 [0 2]
 [0 8]
 [0 9]
 [1 2]
 [1 3]
 [1 9]
 [2 3]
 [2 4]
 [3 4]
 [3 5]
 [4 5]
 [4 6]
 [5 6]
 [5 7]
 [6 7]
 [6 8]
 [7 8]
 [7 9]
 [8 9]]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [ ]:
C = np.array([0, 2, 3, 1, 0])  # np.bincount(A) result

# Reconstruct A
A = np.repeat(np.arange(len(C)), C)

print(A)  
print(np.bincount(A))

[1 1 2 2 2 3]
[0 2 3 1]


75. How to compute averages using a sliding window over an array?

In [15]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
k = 3

# Compute sliding window averages
cumsum = np.cumsum(np.insert(Z, 0, 0))
averages = (cumsum[k:] - cumsum[:-k]) / k

print(averages)

[2. 3. 4. 5. 6. 7. 8. 9.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [16]:
from numpy.lib.stride_tricks import as_strided

# Example array
Z = np.array([0, 1, 2, 3, 4, 5])

# Build shifted 2D array using strides
n = len(Z)
shape = (n - 2, 3)
strides = (Z.strides[0], Z.strides[0])
result = as_strided(Z, shape=shape, strides=strides)

print(result)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


77. How to negate a boolean, or to change the sign of a float inplace?

In [17]:
# Boolean array
bool_arr = np.array([True, False, True, False])
bool_arr = ~bool_arr  # Negate in-place (returns view, but ~ is bitwise not)

# Float array
float_arr = np.array([1.0, -2.0, 3.0])
float_arr *= -1  # Flip sign in-place

print(bool_arr)   # Output: [False  True False  True]
print(float_arr)


[False  True False  True]
[-1.  2. -3.]


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [18]:
P0 = np.array([[0, 0], [1, 1], [2, 3]])  # Start points
P1 = np.array([[1, 0], [2, 2], [3, 1]])  # End points
p = np.array([0.5, 0.5])                 # Query point

# Vectors
A = p - P0
B = P1 - P0

# Cross product magnitude and line lengths
cross = np.abs(A[:, 0] * B[:, 1] - A[:, 1] * B[:, 0])
lengths = np.linalg.norm(B, axis=1)

# Distances
distances = cross / lengths

print(distances)

[0.5        0.         2.45967478]



79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [19]:
P0 = np.array([[0, 0], [1, 1]])  # Start points (n=2)
P1 = np.array([[1, 0], [2, 2]])  # End points (n=2)
P = np.array([[0.5, 0.5], [1.5, 1.5]])  # Query points (m=2)

# Vectors (broadcast P over lines)
A = P[:, np.newaxis, :] - P0[np.newaxis, :, :]  # Shape (m, n, 2)
B = P1[np.newaxis, :, :] - P0[np.newaxis, :, :]  # Shape (m, n, 2)

# Cross product magnitude and line lengths
cross = np.abs(A[:, :, 0] * B[:, :, 1] - A[:, :, 1] * B[:, :, 0])  # Shape (m, n)
lengths = np.linalg.norm(B, axis=2)  # Shape (m, n)

# Distances
distances = cross / lengths

print(distances)

[[0.5 0. ]
 [1.5 0. ]]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [20]:
def extract_subpart(arr, center_idx, shape, fill_value=0):
    """
    Extract a subarray of given shape centered at center_idx, padding with fill_value if needed.
    
    Parameters:
    - arr: Input NumPy array
    - center_idx: Tuple of indices (row, col) for the center
    - shape: Tuple of (height, width) for the subarray
    - fill_value: Value to pad with (default: 0)
    
    Returns:
    - Subarray of specified shape
    """
    rows, cols = shape
    row, col = center_idx
    half_rows, half_cols = rows // 2, cols // 2
    
    # Initialize output array with fill_value
    result = np.full(shape, fill_value, dtype=arr.dtype)
    
    # Compute slice indices for the input array
    row_start = max(0, row - half_rows)
    row_end = min(arr.shape[0], row + half_rows + 1)
    col_start = max(0, col - half_cols)
    col_end = min(arr.shape[1], col + half_cols + 1)
    
    # Compute slice indices for the result array
    res_row_start = max(0, half_rows - row)
    res_row_end = res_row_start + (row_end - row_start)
    res_col_start = max(0, half_cols - col)
    res_col_end = res_col_start + (col_end - col_start)
    
    # Copy the subpart from input array to result
    result[res_row_start:res_row_end, res_col_start:res_col_end] = \
        arr[row_start:row_end, col_start:col_end]
    
    return result

# Example
arr = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
subpart = extract_subpart(arr, center, shape, fill_value=0)
print(subpart)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [21]:
def sliding_window(Z, window_size=4):
    """
    Generate an array of sliding windows from 1D array Z.
    
    Parameters:
    - Z: Input 1D NumPy array
    - window_size: Size of each window
    
    Returns:
    - Array of shape (len(Z) - window_size + 1, window_size)
    """
    shape = (len(Z) - window_size + 1, window_size)
    strides = (Z.strides[0], Z.strides[0])
    return np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides)

# Example
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = sliding_window(Z, window_size=4)

82. Compute a matrix rank

In [22]:
def sliding_window(Z, window_size=4):
    """
    Generate an array of sliding windows from 1D array Z.
    
    Parameters:
    - Z: Input 1D NumPy array
    - window_size: Size of each window
    
    Returns:
    - Array of shape (len(Z) - window_size + 1, window_size)
    """
    shape = (len(Z) - window_size + 1, window_size)
    strides = (Z.strides[0], Z.strides[0])
    return np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides)

# Example
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = sliding_window(Z, window_size=4)

83. How to find the most frequent value in an array?


In [23]:
def most_frequent(arr):
    """
    Find the most frequent value in a NumPy array.
    
    Parameters:
    - arr: Input NumPy array
    
    Returns:
    - Most frequent value
    """
    values, counts = np.unique(arr, return_counts=True)
    return values[np.argmax(counts)]

# Example
arr = np.array([1, 2, 2, 3, 2, 4, 5])
freq = most_frequent(arr)
print(freq)

2


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [24]:
def extract_3x3_blocks(matrix):
    """
    Extract all contiguous 3x3 blocks from a 10x10 matrix.
    
    Parameters:
    - matrix: 10x10 NumPy array
    
    Returns:
    - Array of shape ((10-3+1)*(10-3+1), 3, 3)
    """
    shape = (matrix.shape[0] - 2, matrix.shape[1] - 2, 3, 3)
    strides = matrix.strides + matrix.strides
    blocks = np.lib.stride_tricks.as_strided(matrix, shape=shape, strides=strides)
    return blocks.reshape(-1, 3, 3)

# Example
matrix = np.random.randint(0, 10, (10, 10))
blocks = extract_3x3_blocks(matrix)
print(blocks.shape)

(64, 3, 3)


85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [25]:
class SymmetricArray(np.ndarray):
    """
    A NumPy array subclass ensuring Z[i,j] == Z[j,i].
    """
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        # Ensure symmetry by copying upper triangle to lower
        obj = np.triu(obj) + np.triu(obj, 1).T
        return obj

    def __setitem__(self, idx, value):
        i, j = idx
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)  # Ensure symmetry

# Example
arr = np.zeros((3, 3))
sym_arr = SymmetricArray(arr)
sym_arr[0, 1] = 5
print(sym_arr)


[[0. 5. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [26]:
def sum_matrix_vector_products(matrices, vectors):
    """
    Compute the sum of p matrix-vector products for p (n,n) matrices and p (n,1) vectors.
    
    Parameters:
    - matrices: Array of shape (p, n, n)
    - vectors: Array of shape (p, n, 1)
    
    Returns:
    - Sum of products, shape (n, 1)
    """
    return np.einsum('ijk,ikl->jl', matrices, vectors)

# Example
p, n = 3, 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)
result = sum_matrix_vector_products(matrices, vectors)
print(result.shape)  


(4, 1)


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [27]:
def block_sum(arr, block_size=4):
    """
    Compute the block-sum of a 16x16 array with given block size.
    
    Parameters:
    - arr: 16x16 NumPy array
    - block_size: Size of each block (e.g., 4 for 4x4)
    
    Returns:
    - Array of block sums
    """
    n = arr.shape[0]
    return arr.reshape(n // block_size, block_size, n // block_size, block_size).sum(axis=(1, 3))

# Example
arr = np.ones((16, 16))
sums = block_sum(arr, block_size=4)
print(sums.shape)  
print(sums)  

(4, 4)
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays?

In [28]:
def game_of_life_step(grid):
    """
    Compute one step of Conway's Game of Life using pure NumPy.
    
    Parameters:
    - grid: 2D NumPy array (0s and 1s)
    
    Returns:
    - Next state of the grid
    """
    # Count neighbors using array shifts
    shifts = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
    neighbors = np.zeros_like(grid)
    for di, dj in shifts:
        neighbors += np.roll(np.roll(grid, di, axis=0), dj, axis=1)
    
    # Apply Game of Life rules
    new_grid = np.zeros_like(grid)
    new_grid[(grid == 1) & (neighbors == 2) | (neighbors == 3)] = 1
    new_grid[(grid == 0) & (neighbors == 3)] = 1
    
    return new_grid

# Example usage
grid = np.random.choice([0, 1], size=(10, 10), p=[0.8, 0.2])
new_grid = game_of_life_step(grid)
print(new_grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 0 0 0]
 [0 0 1 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


89. How to get the n largest values of an array 

In [29]:
def n_largest(arr, n):
    """
    Get the n largest values in an array.
    
    Parameters:
    - arr: Input NumPy array
    - n: Number of largest values to return
    
    Returns:
    - Array of n largest values
    """
    return np.partition(arr, -n)[-n:]

# Example
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
n_largest_vals = n_largest(arr, 3)
print(n_largest_vals)

[5 6 9]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [30]:
def cartesian_product(*arrays):
    """
    Compute the Cartesian product of arbitrary number of vectors.
    
    Parameters:
    - arrays: Variable number of 1D NumPy arrays
    
    Returns:
    - Array of shape (prod(len(arrays)), len(arrays))
    """
    return np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))

# Example
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
prod = cartesian_product(a, b, c)
print(prod)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


91. How to create a record array from a regular array? 

In [31]:
def cartesian_product(*arrays):
    """
    Compute the Cartesian product of arbitrary number of vectors.
    
    Parameters:
    - arrays: Variable number of 1D NumPy arrays
    
    Returns:
    - Array of shape (prod(len(arrays)), len(arrays))
    """
    return np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))

# Example
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
prod = cartesian_product(a, b, c)
print(prod)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [32]:
def cube_methods(Z):
    """
    Compute Z^3 using three different methods.
    
    Parameters:
    - Z: 1D NumPy array
    
    Returns:
    - Tuple of three arrays (Z^3 computed differently)
    """
    # Method 1: Element-wise multiplication
    m1 = Z * Z * Z
    
    # Method 2: Power operator
    m2 = Z ** 3
    
    # Method 3: np.power
    m3 = np.power(Z, 3)
    
    return m1, m2, m3

# Example
Z = np.array([1, 2, 3])
m1, m2, m3 = cube_methods(Z)
print(m1, m2, m3) 


[ 1  8 27] [ 1  8 27] [ 1  8 27]


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [33]:
def rows_contain_elements(A, B):
    """
    Find rows in A that contain all elements of any row in B (order-independent).
    
    Parameters:
    - A: Array of shape (8, 3)
    - B: Array of shape (2, 2)
    
    Returns:
    - Indices of matching rows in A
    """
    A_sets = [set(row) for row in A]
    B_sets = [set(row) for row in B]
    indices = []
    for i, a_set in enumerate(A_sets):
        for b_set in B_sets:
            if b_set.issubset(a_set):
                indices.append(i)
                break
    return np.array(indices)

# Example
A = np.random.randint(0, 5, (8, 3))
B = np.array([[1, 2], [3, 4]])
indices = rows_contain_elements(A, B)
print(indices)

[0 1 2 3]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [34]:
def unequal_rows(matrix):
    """
    Extract rows with unequal values from a 10x3 matrix.
    
    Parameters:
    - matrix: 10x3 NumPy array
    
    Returns:
    - Array of rows with unequal values
    """
    return matrix[np.any(matrix[:, 1:] != matrix[:, :-1], axis=1)]

# Example
matrix = np.random.randint(0, 3, (10, 3))
result = unequal_rows(matrix)
print(result)

[[1 1 0]
 [0 1 1]
 [1 0 1]
 [0 1 1]
 [2 0 1]
 [0 0 2]
 [2 2 0]
 [1 2 1]
 [1 0 0]
 [0 2 0]]


95. Convert a vector of ints into a matrix binary representation

In [35]:
def int_to_binary_matrix(vec):
    """
    Convert a vector of integers to a binary matrix representation.
    
    Parameters:
    - vec: 1D NumPy array of integers
    
    Returns:
    - Binary matrix where each row is the binary representation
    """
    n_bits = int(np.ceil(np.log2(vec.max() + 1)))
    return np.array([(vec >> i) & 1 for i in range(n_bits - 1, -1, -1)]).T

# Example
vec = np.array([0, 1, 2, 3])
binary = int_to_binary_matrix(vec)
print(binary)


[[0 0]
 [0 1]
 [1 0]
 [1 1]]


96. Given a two dimensional array, how to extract unique rows?

In [36]:
def unique_rows(arr):
    """
    Extract unique rows from a 2D array.
    
    Parameters:
    - arr: 2D NumPy array
    
    Returns:
    - Array of unique rows
    """
    return np.unique(arr, axis=0)

# Example
arr = np.array([[1, 2], [2, 3], [1, 2], [3, 4]])
unique = unique_rows(arr)
print(unique)

[[1 2]
 [2 3]
 [3 4]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [37]:
def einsum_operations(A, B):
    """
    Compute einsum equivalents of inner, outer, sum, and element-wise multiplication.
    
    Parameters:
    - A, B: 1D NumPy arrays
    
    Returns:
    - Dictionary with results
    """
    return {
        'inner': np.einsum('i,i->', A, B),  # Inner product
        'outer': np.einsum('i,j->ij', A, B),  # Outer product
        'sum': np.einsum('i->', A),  # Sum of A
        'mul': np.einsum('i,i->i', A, B)  # Element-wise multiplication
    }

# Example
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
results = einsum_operations(A, B)
print(results)


{'inner': np.int64(32), 'outer': array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]]), 'sum': np.int64(6), 'mul': array([ 4, 10, 18])}


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

In [38]:
def equidistant_sampling(X, Y, n_samples):
    """
    Sample a path (X, Y) with equidistant points.
    
    Parameters:
    - X, Y: 1D NumPy arrays describing the path
    - n_samples: Number of equidistant samples
    
    Returns:
    - Sampled (X, Y) coordinates
    """
    # Compute cumulative distances
    distances = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
    distances = np.insert(distances, 0, 0)
    
    # Interpolate
    t = np.linspace(0, distances[-1], n_samples)
    x_interp = np.interp(t, distances, X)
    y_interp = np.interp(t, distances, Y)
    
    return x_interp, y_interp

# Example
X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 0, 1])
x_samp, y_samp = equidistant_sampling(X, Y, 10)
print(np.vstack((x_samp, y_samp)).T)


[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]
 [1.33333333 0.66666667]
 [1.66666667 0.33333333]
 [2.         0.        ]
 [2.33333333 0.33333333]
 [2.66666667 0.66666667]
 [3.         1.        ]]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 

In [39]:
def multinomial_rows(X, n):
    """
    Select rows from X that are draws from a multinomial distribution with sum n.
    
    Parameters:
    - X: 2D NumPy array
    - n: Sum of each row
    
    Returns:
    - Rows that are integers and sum to n
    """
    is_integer = np.all(X == X.astype(int), axis=1)
    sums_to_n = np.sum(X, axis=1) == n
    return X[is_integer & sums_to_n]

# Example
X = np.array([[1, 2, 2], [1.5, 1, 1], [2, 1, 2], [0, 0, 0]])
n = 5
result = multinomial_rows(X, n)
print(result)

[[1. 2. 2.]
 [2. 1. 2.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [40]:
def bootstrap_ci(X, n_boot=1000, alpha=0.05):
    """
    Compute bootstrapped 95% confidence intervals for the mean of a 1D array.
    
    Parameters:
    - X: 1D NumPy array
    - n_boot: Number of bootstrap samples
    - alpha: Significance level (default: 0.05 for 95% CI)
    
    Returns:
    - Tuple of (lower_bound, upper_bound)
    """
    boot_means = np.array([np.mean(np.random.choice(X, size=len(X), replace=True)) 
                           for _ in range(n_boot)])
    return np.percentile(boot_means, [100 * alpha / 2, 100 * (1 - alpha / 2)])

# Example
X = np.random.normal(0, 1, 100)
ci = bootstrap_ci(X)
print(ci)

[-0.06842077  0.34733468]
